name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.12.2'
          cabal-version: 'latest'

      - name: Build project
        working-directory: duet-rpc
        run: cabal build --enable-tests

      - name: Run tests
        working-directory: duet-rpc
        run: cabal test
